CREATE USER IF NOT EXISTS 'carrom_user'@'localhost' IDENTIFIED BY 'resortwala@2025';
GRANT ALL PRIVILEGES ON *.* TO 'carrom_user'@'localhost';
CREATE USER IF NOT EXISTS 'kaamcheck_user'@'localhost' IDENTIFIED BY 'resortwala@2025';
GRANT ALL PRIVILEGES ON *.* TO 'kaamcheck_user'@'localhost';
CREATE USER IF NOT EXISTS 'resortwala_user'@'localhost' IDENTIFIED BY 'resortwala@2025';
GRANT ALL PRIVILEGES ON *.* TO 'resortwala_user'@'localhost';
CREATE USER IF NOT EXISTS 'resort_user'@'localhost' IDENTIFIED BY 'resortwala@2025';
GRANT ALL PRIVILEGES ON *.* TO 'resort_user'@'localhost';
CREATE USER IF NOT EXISTS 'resortwala_prod'@'localhost' IDENTIFIED BY 'resortwala@2025';
GRANT ALL PRIVILEGES ON *.* TO 'resortwala_prod'@'localhost';
CREATE USER IF NOT EXISTS 'resortwala_staging'@'localhost' IDENTIFIED BY 'resortwala@2025';
GRANT ALL PRIVILEGES ON *.* TO 'resortwala_staging'@'localhost';
FLUSH PRIVILEGES;
